# Generated by Django 4.0.3 on 2023-09-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='href',
        ),
    ]
